version: '3.8'

services:
  flask1:
    build: .
    container_name: flask-instance-1
    networks:
      - backend

  flask2:
    build: .
    container_name: flask-instance-2
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask1
      - flask2
    networks:
      - backend

networks:
  backend:
    driver: bridge
