version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-node
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nodejs:
    build: .
    container_name: node-app
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: always

volumes:
  db_data:

