version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-limited
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
# docker compose up -d
# docker stats redis-limited
