version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 5

  nodejs:
    build: .
    container_name: node-app
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    restart: always

volumes:
  mongo_data:
